# Generated by Django 5.2.8 on 2025-11-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedata',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
